version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: backend
    restart: always
    environment:
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
    ports:
      - "${BACKEND_APP_PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb

volumes:
  mongo_data:
